Repository LewisRye/cpp-chess, pull requests merged in 2023-12, with the labels that each got.

#1 moves are now working
  Board.cpp
Labels: enhancement

#2 Implemented take piece
  Board.cpp
Labels: enhancement

#3 Implementing move
  Pieces/Pawn.cpp
Labels: bug

#4 bishop implemented
  Pieces/Bishop.cpp
Labels: enhancement

#5 implement rook
  Pieces/Rook.cpp
Labels: enhancement

#6 implemented queen
  Pieces/Queen.cpp
Labels: enhancement

#10 fixed crash in King.cpp
  Pieces/King.cpp
Labels: bug

#9 Update README
  README.md
Labels: documentation

#12 added knight into check branch
  Pieces/Knight.cpp
Labels: enhancement

#13 Implemented check
  Board.cpp
  ChessGame.cpp
  Makefile_Windows
  Pieces/Bishop.cpp
  Pieces/King.cpp
  Pieces/Knight.cpp
  Pieces/Pawn.cpp
  Pieces/Queen.cpp
  Pieces/Rook.cpp
Labels: enhancement

#14 pulling to sound
  Board.cpp
  ChessGame.cpp
  Makefile_Windows
  Pieces/Bishop.cpp
  Pieces/King.cpp
  Pieces/Knight.cpp
  Pieces/Pawn.cpp
  Pieces/Queen.cpp
  Pieces/Rook.cpp
Labels: enhancement
